-- Types ENUM spécifiques à Postgres
CREATE TYPE user_role_enum AS ENUM ('candidat', 'recruteur');
CREATE TYPE score_decision_enum AS ENUM ('EXCELLENT', 'BON', 'MOYEN', 'FAIBLE');

-- TABLES

CREATE TABLE agent_validation_memory (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id        varchar(20) NOT NULL,
  validation_status varchar(30) NOT NULL,
  feedback_comment text,
  candidate_id    integer,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE candidates (
  id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_agent          varchar(9) NOT NULL,
  nom               varchar(100) NOT NULL,
  prenom            varchar(100) NOT NULL,
  titre_profil      varchar(255),
  categorie_profil  varchar(50),
  ville             varchar(100),
  pays              varchar(100),
  linkedin          varchar(255),
  github            varchar(255),
  behance           varchar(255),
  email             varchar(255),
  phone             varchar(20),
  annees_experience integer,
  disponibilite     varchar(50),
  pret_a_relocater  varchar(10),
  niveau_seniorite  text,
  resume_bref       text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  image_minio_url   varchar(500),
  candidate_uuid    varchar(36),
  pays_cible        varchar(255),
  constraints       text,
  search_criteria   text,
  salaire_minimum   varchar(50),
  embedding         jsonb,
  user_id           integer,
  type_contrat      text
);

CREATE TABLE candidate_postule (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id          integer NOT NULL,
  candidate_id    integer NOT NULL,
  validated_at    timestamptz NOT NULL DEFAULT now(),
  note            text,
  validate        boolean DEFAULT false,
  use_tap_cv      boolean,
  status          varchar(20)
);

CREATE TABLE email_verification_tokens (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    integer NOT NULL,
  code       varchar(10) NOT NULL,
  expires_at timestamptz NOT NULL,
  used       boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE fichiers_versions (
  id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id            integer NOT NULL,
  candidate_uuid          varchar(36) NOT NULL,
  corrected_json_minio_url varchar(500),
  corrected_pdf_minio_url varchar(500),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  talent_card_url         varchar(500),
  cv_ancienne_url         varchar(500),
  long_pdf_url            varchar(500),
  long_ancienne_url       varchar(500),
  one_page_pdf_url        varchar(500)
);

CREATE TABLE jobs (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title            varchar(255) NOT NULL,
  categorie_profil varchar(50),
  niveau_attendu   varchar(50),
  experience_min   varchar(50),
  presence_sur_site varchar(100),
  reason           text,
  main_mission     text,
  tasks_other      varchar(500),
  disponibilite    varchar(50),
  salary_min       numeric(12,2),
  salary_max       numeric(12,2),
  urgent           boolean DEFAULT false,
  location_type    jsonb,
  tasks            jsonb,
  soft_skills      jsonb,
  skills           jsonb,
  languages        jsonb,
  contrat          varchar(20) DEFAULT 'stage',
  niveau_seniorite varchar(20),
  created_at       timestamptz NOT NULL DEFAULT now(),
  entreprise       varchar(50),
  embedding        jsonb NOT NULL,
  user_id          integer
);

CREATE TABLE score (
  id                             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id                   integer NOT NULL,
  created_at                     timestamptz NOT NULL DEFAULT now(),
  engine_version                 varchar(50) DEFAULT 'CORE_V1_STABLE',
  sector_detected                varchar(100),
  score_global                   numeric(5,2) NOT NULL,
  dim_impact                     numeric(5,2) NOT NULL,
  dim_impact_base                numeric(5,2) NOT NULL,
  dim_impact_bonus_maturite      numeric(5,2) DEFAULT 0.00,
  dim_impact_penalite            numeric(5,2) DEFAULT 0.00,
  impact_precision_score         numeric(5,2) NOT NULL,
  impact_ampleur_score           numeric(5,2) NOT NULL,
  impact_portee_score            numeric(5,2) NOT NULL,
  impact_repetition_score        numeric(5,2) NOT NULL,
  impact_nature_coeff            numeric(5,2) NOT NULL,
  dim_hard_skills_depth          numeric(5,2) NOT NULL,
  hs_complexite_score            numeric(5,2) NOT NULL,
  hs_maitrise_score              numeric(5,2) NOT NULL,
  hs_autonomie_score             numeric(5,2) NOT NULL,
  hs_type_problemes_score        numeric(5,2) NOT NULL,
  hs_transversalite_score        numeric(5,2) NOT NULL,
  dim_coherence                  numeric(5,2) NOT NULL,
  coherence_progression_score    numeric(5,2) NOT NULL,
  coherence_continuite_score     numeric(5,2) NOT NULL,
  coherence_logique_sectorielle_score numeric(5,2) NOT NULL,
  dim_rarete_marche              numeric(5,2) NOT NULL,
  rarete_densite_score           numeric(5,2) NOT NULL,
  rarete_combinaison_score       numeric(5,2) NOT NULL,
  rarete_contribution_score      numeric(5,2) NOT NULL,
  dim_stabilite                  numeric(5,2) NOT NULL,
  stabilite_coherence_parcours_score numeric(5,2) NOT NULL,
  stabilite_duree_score          numeric(5,2) NOT NULL,
  stabilite_engagement_score     numeric(5,2) NOT NULL,
  dim_communication              numeric(5,2) NOT NULL,
  communication_clarte_score     numeric(5,2) NOT NULL,
  communication_structure_score  numeric(5,2) NOT NULL,
  communication_precision_score  numeric(5,2) NOT NULL,
  communication_densite_score    numeric(5,2) NOT NULL,
  decision                       score_decision_enum,
  commentaire                    text
);

CREATE TABLE skills_score (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    varchar(255) NOT NULL,
  score   numeric(4,2) NOT NULL,
  status  varchar(50) NOT NULL,
  scope   varchar(50) NOT NULL
);

CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         varchar(255) NOT NULL,
  password_hash varchar(255) NOT NULL,
  role          user_role_enum NOT NULL,
  is_verified   boolean NOT NULL DEFAULT false,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

-- INDEXES (équivalents aux KEY/UNIQUE MySQL)

CREATE INDEX idx_agent_id ON agent_validation_memory (agent_id);
CREATE INDEX idx_created_at ON agent_validation_memory (created_at);
CREATE INDEX idx_agent_created ON agent_validation_memory (agent_id, created_at);

CREATE UNIQUE INDEX candidates_id_agent_key ON candidates (id_agent);
CREATE INDEX candidates_user_id_idx ON candidates (user_id);

CREATE UNIQUE INDEX uk_job_candidate ON candidate_postule (job_id, candidate_id);
CREATE INDEX idx_job ON candidate_postule (job_id);
CREATE INDEX idx_candidate ON candidate_postule (candidate_id);
CREATE INDEX idx_validated_at ON candidate_postule (validated_at);

CREATE INDEX idx_evt_user ON email_verification_tokens (user_id);
CREATE INDEX idx_evt_code ON email_verification_tokens (code);

CREATE INDEX idx_candidate_uuid ON fichiers_versions (candidate_uuid);
CREATE INDEX idx_candidate_id ON fichiers_versions (candidate_id);

CREATE INDEX jobs_user_id_idx ON jobs (user_id);

CREATE INDEX idx_candidate_score ON score (candidate_id, score_global);
CREATE INDEX idx_created ON score (created_at);

CREATE UNIQUE INDEX users_email_key ON users (email);

-- FOREIGN KEYS

ALTER TABLE candidates
  ADD CONSTRAINT fk_candidates_user
  FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE candidate_postule
  ADD CONSTRAINT candidate_postule_job_fk
  FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
  ADD CONSTRAINT candidate_postule_candidate_fk
  FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE;

ALTER TABLE fichiers_versions
  ADD CONSTRAINT fichiers_versions_candidate_fk
  FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE;

ALTER TABLE jobs
  ADD CONSTRAINT fk_jobs_user
  FOREIGN KEY (user_id) REFERENCES users (id);